"""Generate the paper's LaTeX tables from results/.

Emits \\input-able fragments so that no number in the manuscript is ever typed
by hand. Regenerating results and recompiling is sufficient to update the paper.
"""

from __future__ import annotations

import json
import sys

import pandas as pd

from config import RESULTS, TARGET_LOADS

TEX = RESULTS.parent / "paper" / "tables"
TEX.mkdir(parents=True, exist_ok=True)

WL = {"conv": "Conversation", "code": "Code"}

POLICY_ORDER = [
    "fcfs", "sjf_context", "predicted_sjf", "cb_sjf_work",
    "oracle_sjf", "oracle_work",
]
POLICY_TEX = {
    "fcfs": "FCFS (engine default)",
    "sjf_context": "SJF-Ctx",
    "predicted_sjf": "SJF-Pred",
    "cb_sjf_work": r"\textbf{CB-SJF-Work (ours)}",
    "oracle_sjf": r"\quad Oracle-SJF$^\dagger$",
    "oracle_work": r"\quad Oracle-Work$^\dagger$",
}

HIGH_LOAD = 0.92   # representative contended operating point


def _w(name: str, body: str):
    (TEX / name).write_text(body)
    print(f"wrote paper/tables/{name}")


def table_workloads():
    ws = json.loads((RESULTS / "work_share.json").read_text())
    head = json.loads((RESULTS / "headline.json").read_text())

    rows = []
    for wl in ("conv", "code"):
        w, h = ws[wl], head[wl]
        rows.append(
            f"{WL[wl]} & {w['n_requests']/1e6:.1f}M & "
            f"{w['mean_context_tokens']:.0f} & {w['mean_output_tokens']:.0f} & "
            f"{w['prefill_pct']:.1f} & {h['predictor_spearman']:.3f} & "
            f"{h['predictor_pairwise_acc']:.3f} \\\\"
        )

    body = r"""% Auto-generated by src/tables.py -- do not edit by hand.
\begin{table}[!t]
\caption{Azure production trace characteristics. Prefill share is the fraction
of total schedulable work that is exactly observable at admission time.
$\rho_s$ and pairwise accuracy measure how well the content-blind predictor
recovers true output length.}
\label{tab:workloads}
\centering
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
 & & \multicolumn{2}{c}{Mean tokens} & Prefill & \multicolumn{2}{c}{Predictor} \\
\cmidrule(lr){3-4}\cmidrule(lr){6-7}
Workload & Reqs. & Ctx. & Out. & share (\%) & $\rho_s$ & Pair.\ acc. \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    _w("workloads.tex", body)


def table_main():
    df = pd.DataFrame(json.loads((RESULTS / "raw" / "runs.json").read_text()))
    sub = df[df.target_load == HIGH_LOAD]

    lines = []
    for pol in POLICY_ORDER:
        cells = []
        for wl in ("conv", "code"):
            c = sub[(sub.workload == wl) & (sub.policy == pol)]
            g = c["norm_latency_mean"]
            p99 = c["latency_p99"] / 1000.0
            slo = c["slo_both_attain"] * 100
            cells += [
                f"{g.mean():.0f}\\,$\\pm$\\,{g.std():.0f}",
                f"{p99.mean():.0f}",
                f"{slo.mean():.1f}",
            ]
        lines.append(f"{POLICY_TEX[pol]} & " + " & ".join(cells) + r" \\")
        if pol == "cb_sjf_work":
            lines.append(r"\midrule")

    body = r"""% Auto-generated by src/tables.py -- do not edit by hand.
\begin{table*}[!t]
\caption{Scheduling performance at offered load $\rho=""" + f"{HIGH_LOAD:.2f}" + r"""$,
averaged over five disjoint 20-minute windows of production traffic
(mean\,$\pm$\,s.d.). $\bar{L}_n$ is mean normalised latency (ms per output
token); $P_{99}$ is 99th-percentile end-to-end latency (s); SLO is the
fraction of requests meeting both the TTFT and TBT targets.
$^\dagger$Oracle policies require knowledge unavailable at admission time and
are upper bounds, not deployable systems.}
\label{tab:main}
\centering
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
& \multicolumn{3}{c}{Conversation} & \multicolumn{3}{c}{Code} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
Policy & $\bar{L}_n$ & $P_{99}$ (s) & SLO (\%) & $\bar{L}_n$ & $P_{99}$ (s) & SLO (\%) \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table*}
"""
    _w("main_results.tex", body)


def table_recovery():
    t = pd.read_csv(RESULTS / "paired_tests.csv")
    rows = []
    for wl in ("conv", "code"):
        s = t[t.workload == wl].sort_values("target_load")
        imp = " & ".join(f"{v:.1f}" for v in s.improvement_pct)
        rec = " & ".join(f"{v:.1f}" for v in s.oracle_gap_recovered_pct)
        rows.append(f"{WL[wl]} & improvement & {imp} \\\\")
        rows.append(f" & oracle gap rec. & {rec} \\\\")

    loads = " & ".join(f"{L:.2f}" for L in TARGET_LOADS)
    body = r"""% Auto-generated by src/tables.py -- do not edit by hand.
\begin{table}[!t]
\caption{Reduction in mean normalised latency achieved by CB-SJF-Work relative
to FCFS, and the percentage of the attainable oracle improvement that it
recovers, as a function of offered load. All improvements are consistent across
all five windows (Wilcoxon signed-rank, $p=0.031$, the minimum attainable at
$n=5$).}
\label{tab:recovery}
\centering
\begin{tabular}{@{}llrrrrr@{}}
\toprule
& & \multicolumn{5}{c}{Offered load $\rho$} \\
\cmidrule(lr){3-7}
Workload & Quantity (\%) & """ + loads + r""" \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    _w("recovery.tex", body)


def main() -> int:
    table_workloads()
    table_main()
    table_recovery()
    return 0


if __name__ == "__main__":
    sys.exit(main())
