"""Generate the paper's LaTeX tables from results/.

Emits \\input-able fragments so that no number in the manuscript is ever typed
by hand. Regenerating results and recompiling is sufficient to update the paper.
"""

from __future__ import annotations

import json
import sys

import pandas as pd

from config import RESULTS, TARGET_LOADS

TEX = RESULTS.parent / "paper" / "tables"
TEX.mkdir(parents=True, exist_ok=True)

WL = {"conv": "Conversation", "code": "Code"}

POLICY_ORDER = [
    "fcfs", "sjf_context", "predicted_sjf", "cb_sjf_work",
    "oracle_sjf", "oracle_work",
]
POLICY_TEX = {
    "fcfs": "FCFS (engine default)",
    "sjf_context": "SJF-Ctx",
    "predicted_sjf": "SJF-Pred",
    "cb_sjf_work": r"\textbf{CB-SJF-Work (ours)}",
    "oracle_sjf": r"\quad Oracle-SJF$^\dagger$",
    "oracle_work": r"\quad Oracle-Work$^\dagger$",
}

HIGH_LOAD = 0.92   # representative contended operating point


def _w(name: str, body: str):
    (TEX / name).write_text(body)
    print(f"wrote paper/tables/{name}")


def table_workloads():
    ws = json.loads((RESULTS / "work_share.json").read_text())
    head = json.loads((RESULTS / "headline.json").read_text())

    rows = []
    for wl in ("conv", "code"):
        w, h = ws[wl], head[wl]
        rows.append(
            f"{WL[wl]} & {w['n_requests']/1e6:.1f}M & "
            f"{w['mean_context_tokens']:.0f} & {w['mean_output_tokens']:.0f} & "
            f"{w['prefill_pct']:.1f} & {h['predictor_spearman']:.3f} & "
            f"{h['predictor_pairwise_acc']:.3f} \\\\"
        )

    body = r"""% Auto-generated by src/tables.py -- do not edit by hand.
\begin{table}[!t]
\caption{Azure production trace characteristics. Prefill share is the fraction
of total schedulable work that is exactly observable at admission time.
$\rho_s$ and pairwise accuracy measure how well the content-blind predictor
recovers true output length.}
\label{tab:workloads}
\centering
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
 & & \multicolumn{2}{c}{Mean tokens} & Prefill & \multicolumn{2}{c}{Predictor} \\
\cmidrule(lr){3-4}\cmidrule(lr){6-7}
Workload & Reqs. & Ctx. & Out. & share (\%) & $\rho_s$ & Pair.\ acc. \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    _w("workloads.tex", body)


def table_main():
    df = pd.DataFrame(json.loads((RESULTS / "raw" / "runs.json").read_text()))
    sub = df[df.target_load == HIGH_LOAD]
    nwin = {wl: int(sub[sub.workload == wl].window.nunique()) for wl in ("conv", "code")}

    lines = []
    for pol in POLICY_ORDER:
        cells = []
        for wl in ("conv", "code"):
            c = sub[(sub.workload == wl) & (sub.policy == pol)]
            g = c["norm_latency_mean"]
            p99 = c["latency_p99"] / 1000.0
            slo = c["slo_both_attain"] * 100
            cells += [
                f"{g.mean():.0f}\\,$\\pm$\\,{g.std():.0f}",
                f"{p99.mean():.0f}",
                f"{slo.mean():.1f}",
            ]
        lines.append(f"{POLICY_TEX[pol]} & " + " & ".join(cells) + r" \\")
        if pol == "cb_sjf_work":
            lines.append(r"\midrule")

    body = r"""% Auto-generated by src/tables.py -- do not edit by hand.
\begin{table*}[!t]
\caption{Scheduling performance at offered load $\rho=""" + f"{HIGH_LOAD:.2f}" + r"""$,
averaged over """ + f"{nwin['conv']}" + r""" (conversation) and """ + f"{nwin['code']}" + r"""
(code) disjoint windows sampled across the full week (mean\,$\pm$\,s.d.).
$\bar{L}_n$ is mean normalised latency (ms per output token); $P_{99}$ is
99th-percentile end-to-end latency (s); SLO is the fraction of requests meeting
both the TTFT and TBT targets. Note that every work- or length-aware policy,
including both oracles, degrades $P_{99}$ relative to FCFS: ordering short
requests first defers long ones by construction.
$^\dagger$Oracle policies require knowledge unavailable at admission time and
are upper bounds, not deployable systems.}
\label{tab:main}
\centering
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
& \multicolumn{3}{c}{Conversation} & \multicolumn{3}{c}{Code} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
Policy & $\bar{L}_n$ & $P_{99}$ (s) & SLO (\%) & $\bar{L}_n$ & $P_{99}$ (s) & SLO (\%) \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table*}
"""
    _w("main_results.tex", body)


def table_recovery():
    t = pd.read_csv(RESULTS / "paired_tests.csv")
    tail = pd.read_csv(RESULTS / "tail_analysis.csv")
    rows = []
    for wl in ("conv", "code"):
        s = t[t.workload == wl].sort_values("target_load")
        h = tail[tail.workload == wl].sort_values("target_load")
        imp = " & ".join(f"{v:.1f}" for v in s.improvement_pct)
        rng = " & ".join(
            f"{lo:.0f}--{hi:.0f}"
            for lo, hi in zip(
                s.improvement_pct_perwindow_min, s.improvement_pct_perwindow_max
            )
        )
        rec = " & ".join(f"{v:.1f}" for v in s.oracle_gap_recovered_pct)
        p99 = " & ".join(f"{v:.2f}" for v in h.p99_ratio_mean)
        rows.append(f"{WL[wl][:4]}. & improvement & {imp} \\\\")
        rows.append(f" & \\quad range & {rng} \\\\")
        rows.append(f" & oracle gap & {rec} \\\\")
        rows.append(f" & $P_{{99}}$/FCFS & {p99} \\\\")
        rows.append(r"\addlinespace")

    loads = " & ".join(f"{L:.2f}" for L in TARGET_LOADS)
    body = r"""% Auto-generated by src/tables.py -- do not edit by hand.
\begin{table}[!t]
\caption{CB-SJF-Work relative to FCFS against offered load. Rows per workload:
mean-latency improvement (\%); its per-window range (\%); percentage of the
oracle-attainable improvement recovered; and the ratio of 99th-percentile
latency to FCFS, where a value above 1.0 means the tail is worse. The first
three rows are the benefit, the fourth is the cost.}
\label{tab:recovery}
\centering\footnotesize\setlength{\tabcolsep}{3.5pt}
\begin{tabular}{@{}llrrrrr@{}}
\toprule
& & \multicolumn{5}{c}{Offered load $\rho$} \\
\cmidrule(lr){3-7}
Workload & Quantity & """ + loads + r""" \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    _w("recovery.tex", body)


def table_sensitivity():
    g = pd.read_csv(RESULTS / "sensitivity_genlen.csv")
    c = pd.read_csv(RESULTS / "sensitivity_cache.csv")

    rows = []
    for wl in ("conv", "code"):
        s = g[g.workload == wl].sort_values("gen_scale")
        rows.append(
            f"{WL[wl]} & " + " & ".join(f"{v:.0f}" for v in s.prefill_time_share_pct)
            + r" \\"
        )
        rows.append(
            " & " + " & ".join(f"{v:.0f}" for v in s.improvement_pct) + r" \\"
        )
        rows.append(
            " & " + " & ".join(f"{v:.2f}" for v in s.cb_over_oracle_ratio) + r" \\"
        )
        rows.append(
            " & " + " & ".join(f"{v:.1f}" for v in s.predictor_gain_pct) + r" \\"
        )
        rows.append(r"\addlinespace")

    crows = []
    for wl in ("conv", "code"):
        s = c[c.workload == wl].sort_values("cache_hit")
        crows.append(
            f"{WL[wl]} & " + " & ".join(f"{v:.0f}" for v in s.improvement_pct) + r" \\"
        )

    scales = " & ".join(f"{v:.0f}$\\times$" for v in
                        sorted(g.gen_scale.unique()))
    hits = " & ".join(f"{v:.0%}".replace("%", r"\%") for v in
                      sorted(c.cache_hit.unique()))

    body = r"""% Auto-generated by src/tables.py -- do not edit by hand.
\begin{table}[!t]
\caption{Robustness at $\rho=0.92$. Top: scaling output length, which drives the
prefill share of engine time down and models longer-generation workloads. The
improvement over FCFS survives, but the penalty for content-blindness
(CB/Oracle-Work ratio) grows and the learned predictor becomes worthwhile.
Bottom: modelling a prefix-cache hit rate, which shrinks the observable work and
substantially reduces the benefit of any work-aware ordering.}
\label{tab:sens}
\centering\footnotesize\setlength{\tabcolsep}{4pt}
\begin{tabular}{@{}lrrrrr@{}}
\toprule
\multicolumn{6}{@{}l}{\textit{(a) Output-length scaling}} \\
& """ + scales + r""" \\
\midrule
""" + "\n".join(rows) + r"""
\midrule
\multicolumn{6}{@{}l}{\textit{(b) Prefix-cache hit rate}} \\
& """ + hits + r""" & \\
\midrule
""" + "\n".join(crows) + r"""
\bottomrule
\end{tabular}
\begin{flushleft}\scriptsize
(a) Rows per workload: prefill share of engine time (\%); improvement over FCFS
(\%); CB-SJF-Work/Oracle-Work latency ratio ($\times$); predictor gain over
SJF-Ctx (\%). (b) Improvement over FCFS (\%).
\end{flushleft}
\end{table}
"""
    _w("sensitivity.tex", body)


def main() -> int:
    table_workloads()
    table_main()
    table_recovery()
    table_sensitivity()
    return 0


if __name__ == "__main__":
    sys.exit(main())
